env:
  global:
    - CC_TEST_REPORTER_ID=4061d1f19a14b3a8cf7a721701a4c96426861c793f1709e445256fa37bcb255f
    -
sudo: false
language: ruby
rvm:
  - 2.4
before_install: gem install bundler -v 1.14.6

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - COVERAGE=1 rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
